git:
  depth: 3
  quite: true
language: csharp
mono: latest
install: true
script: nuget pack ./src/ZhusTemplate.nuspec
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push *.nupkg -ApiKey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
  on:
    tags: true
env:
  global:
    secure: HRe/jCa4aXqDQAygD0alhaeL5S2V3qcbh+9jY4GfpTjAIBq/YeZS4A6mUTWTnJaZqbOkQXq4edhCjMOyft+w0A+Hv79c3WvNk7AicfBmFoPZTWztuq9imHaWEOiiouocIJR8GrtxNt5VCKW4RCa2A/2XRozTQqeKhBfmw0Mi4IlDjTNMZNZzDUmKQhGqUpRkbg7A78+q95Mq6zwU2V07cylwxRUl2p+WNmBZlSrbOg2boBfosZ/eARDXRq1sGVivNA1kxLVVxSmjmbTWERjaax5kCY3JMV4/LkGJucnuSg+PKP/bpxrVhT1uTh4x2Z6eZjRtTyIlpdWhJedlDiJALAd9dPy/SP88zDw8lid6JzI9MuxdVH1hXi1oY5KbQiRsU6AG8pJqEWV+xvUXEkZqNPRxy3f/ZUlQGnAOXSQY14cg+oOjcmKuwRhPzpRRO5h6yLc51rKLHxgFlkYdZlRcd9U3MguQfYo7AFVkiEK/J5jo5rFPa9MEj5LMGqDNaCZ2Z2aIzhjbP7vEO46pVEZap74qlAbzCdPaXpltisk1QS9xTfF84MT9Q2advVIo2NV0wByD5XzQguLBLXcgNcyMn9rnD4EuIdqcPgIjmW4h+koNmQGovOzQ/Sp+BjY/ftkomwmP9o8FUlb2+9QimEwo/MZEpbZy08+ORb1HeJkYFrw=
