git:
  depth: 3
  quite: true
language: csharp
mono: latest
install: true
script: nuget pack ./ZhusTemplate.nuspec
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push *.nupkg -ApiKey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
  on:
    tags: true
env:
  global:
    secure: m2A5IJ2lePU7E1EXcjQn88w2kc4+PeNajUrwu8m+WEPrYATnTfv5WJrD9d/N3fuFgbDhAiFVgTfx3mzB8xJu4f7YOj063yj4qx4y/a71BQ+PtCsLStfFkRNYO6sZLCIRJV9j5NCZNlnC+KKqEC5t/4DilVY3cA4oYG+wgw+vPvE5tnbnyO7xnDF88bb+wFJRJ5DqnHJcgkZIDX913kF+74fHFlgMotetZ+qQBW3UA+JR2hx1ljzvkthQb6JSZLmpkJabyY3S5adCoKFAVd/NV1LScmq4lm6hg5/kjOHN2GJOEmAHA2cSmGp1WmNsKFmlwRC8UE/f+ib0pFzOiiIsv8qZzWX7g3CoBEqHnWMWp6a5NuR2gNRyqRRmG1dvLbUyhazsJ8Ys7zc9uhDDD+bsjXVG2jxpmxsv0Ngqu53VdpGe+iiFqGX/SVi810WPQpzXVPWNP0UqFjdY8VQB/XV4nu0XoBC6YES+B7xtVgv7AsPrAfOJmxHCm8QNorreT91e3dsF7/Ti0bMsCn+Gn3FiSjfEY/zmX1HDxaGxYfwrIRttGV6XjchFiAPGQhPzjKcMJIPciUYDKmCEA1NJDKu/TAdnSF2ZRaEGIHN4P5AWezH9pyJIOb2vn6n2OdeDnIPhIOI//hJlkkNbKsNUOxv8tKZqHAP86OSt8Ojh3OyyfKM=
