git:
  depth: 3
  quite: true
language: csharp
mono: latest
install: true
script: nuget pack ./src/ZhusTemplate.nuspec
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push *.nupkg -ApiKey $NUGET_API_KEY -Source https://api.nuget.org/v3/index.json
  on:
    tags: true
env:
  global:
    secure: XOYL95C3Huer+vKMe8lbnRuaBUAZmJjQfIa23AmFreeuK3n/AbqC0PaIX0bV1jtb5GDrNmsg0TU6We5BEotcJBqA+LyFt88WLqM7NuUNtyxV/YKQhAy92ddNlEg9UExKxNP3cXvTreXs3wgbpK12KsMyjG/Toa9pciRZz48F0AM6JMlbm4AUsGxMUmdrsJfINmi3mF9jWgD7NcVPbc33rb5zNljf63IkGuu+E3mTAjrgEjZJtiJzLg9Sg/UKPhxQ/M5yxaP1nCKs/vYPNGjWqnb7X693jnNlT1FrsacrEvEXR1Nn7qOHC5CbptruKVKaxIeVrMvzji8CR+jippTdrxQbNaWCVuBM1+g+WZ3A+cEkgdZ2ecxgni2sE/NNvbiVOdvrmNgugtgLWg1DvWXe63yEC5KYXTJ6Ur8BAPbm77ikIw4r4+zX2zDUj0k2rFrneC3oOK8hzDGdwJjg9KWz9TVfu+4vF68eHKvD/H16bF4oW4ULGzSrj2sBlm2Xfecro4up+a8lw5RiFuL7fu6C9Cn7dKp5bKZK6drQ0xZbLYy9wPJ3j8Hm7zIzLirjoPHbwW9MAgJW9sCv7FcKhrimONfwjXu6jetC6w69l3jYIlZN60WHBjb/oNJQh7foIVyNxvrX8mwBAolWwPcqsKZrk4WRQ3dn0edpb+1d4uzCkrA=
