git:
  depth: 3
  quite: true
language: csharp
mono: latest
install: true
script: nuget pack ./ZhusTemplate.nuspec
deploy:
  skip_cleanup: true
  provider: script
  script: nuget push *.nupkg -ApiKey $NUGET_API_KEY -Source $NUGET_PUSH_SOURCE
  on:
    tags: true
env:
  global:
  - secure: X+IhvxPta8I2mR0NgRhQKiR/sjzcHbkyCzOkWBHO638JPehF80kwUgpqXVKhammzmOhJjiswqLwYBeLo+fUH0++PYZ19kO5FS5QMCv9Fd9oVzn7B26QQT0JzYyQagTGzF+kbmh5frDzU4ZxOIC1w8pEYPOS8u4BULIObIWZpEntQ+jtMKv9HTw6joYgWbVitI3tUBBcJoobQdZYqaAYD3YGtXmfPWuOqwS42KwJwhpzrvFr1Lqs1/EZgfl5AslL/yugMKy2OGGSXVZ3Ise8h3KAeKYR9EJ/74FRqP/iFw+CaRuM9B7W6a8ozVt/buXTI2HfoH6Ggh6QuOeNXWrJgRXivdDwBT1ruvzERy7zM2CNSXIhFahKj6pREQTRt1y11FMCaK6W0k5kg1cqdaIwGjBUgxNjTKRgtdBkz07VF0puAU9KITFexO1CDgp9I8+5LcLxKc2f/ef0zxkATF2K6gVzBudZOH4CVbN4sOhYbhp8FYbWbVkFXWyIx5LWPSzw3P9zvKywpN8NF5gl5p5rNvZTomk5Enx2Hr6RhKFsp9WYBrOx3p7WmDBpZwOfFRsJe/F4paf6jISHwUlQnIn1Mrr8w0t8uW20eqKU3XxqonxcT+tIZQuIqygN8DyXZwIdBtMSX7SyerDNa3VXdcVNFyGB0SpWfFGny0OrMM7WGEHc=
  - secure: jHg4nZzEzK6WOBu3Nb4vPPZATLdzFILGdkMF21HLj963p03YZE9Te06kPEPYODBzb7nbuigM89z82FxFFeJvlDSvoKqMSCd6dCTMWgbIQywiFJLvTZB/8eoXtYvNU8ookj6Ho0feGhTyRldEqvDkEz0msvPK8/3AR4aZbcmveBJ0Ymww58BYU99yMEVBpkrjBtgx2UxEKGTPxB1quD8Kiurr2euNZb9KiU1VEd4G2faBh90/7KSL4eI3a/6z4M4jSOz5Mx7FRTDZu9z/3h88wJN2vxzvylUaOZrTNvjYhFWkL9fs0YcKMrjTI0IriYay5lwgI/3Vqw7TG+kB5ZiaPb93MbPOQSd6ffyzmeXDY9mKdRUk7cZIHCHexZQiycz/OVX4Z3PNHRcMVcgIrsZ7DJv0xxacqtKs2zU5StmMru9u+T0Y+z0xtg8bicwFAAIAyB2lTdrvghg1XypGizp/xM3U9v49WgGOZczlmsbiwvXQ6+xLrexMdPL4261/aRDJZJLm5rVLBBEYCzO8FAwhrSF5FIs4d+3AUQeQm+TLsl+gwXC7wdWl3v5ytl2h5TKRFGWjElU4j1/dr8w/1KTo/Fz4N/k0wzQ+saaUq4xIN1ouE45jnjW3hz0xbULhQ7wKwLR3h0LZTVSbj2+meTRac/XXTkAYIoHu2N34DZto/m4=
