# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: NuGetToolInstaller@0
  inputs:
    displayName: 'Download compatible Nuget'
    versionSpec: '4.8.1'
- task: NuGetCommand@2
  inputs:
    displayName: 'Pack the template with NuGet'
    command: 'pack'
    searchPatternPack: '**/*.nuspec'
    packDestination: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: '_DotnetNewTemplate'
